using System;
using System.IO;
using System.Timers;
using NLog;

namespace FxWorth
{
    /// <summary>
    /// The `ApiCompliance` class ensures compliance with the Deriv API terms and conditions regarding 'data storage'.
    /// It manages the log files generated by the application, moving older files to an archive folder 
    /// and deleting archived files that exceed the allowed retention period. This helps prevent 
    /// excessive data storage and ensures compliance with the API's data retention policies.
    /// </summary>
    public class ApiCompliance
    {
        /// The path to the folder where the application's log files are stored.
        private readonly string logFolderPath;

        /// The path to the folder where archived log files are moved.
        private readonly string archiveFolderPath;

        /// The timer that triggers the log file management tasks.
        private readonly Timer timer;

        /// <summary>
        /// Constructor for the `ApiCompliance` class.
        /// Initializes the log and archive folder paths, creates the archive folder if necessary,
        /// and sets up the timer to trigger log file management tasks periodically.
        /// <param name="logFolderPath">The path to the folder containing the active log files.</param>
        /// <param name="archiveFolderPath">The path to the folder where archived log files will be stored.</param>
        /// </summary>
        public ApiCompliance(string logFolderPath, string archiveFolderPath)
        {
            // Store the provided folder paths.
            this.logFolderPath = logFolderPath;
            this.archiveFolderPath = archiveFolderPath;

            // Create the archive folder if it doesn't already exist.
            if (!Directory.Exists(archiveFolderPath))
            {
                Directory.CreateDirectory(archiveFolderPath);
            }

            // Initialize the timer to trigger every 10 minutes (10 * 60 * 1000 milliseconds).
            this.timer = new Timer(10 * 60 * 1000);
            // Attach the `OnTimerElapsed` event handler to be called when the timer interval elapses.
            this.timer.Elapsed += OnTimerElapsed;
        }

        /// <summary>
        /// Starts the API compliance process by starting the timer. 
        /// This initiates the periodic log file management tasks.
        /// </summary>
        public void Start()
        {
            timer.Start();
        }

        /// <summary>
        /// Event handler triggered when the timer interval elapses.
        /// Calls the methods to move old log files to the archive folder and delete old archived files.
        /// <param name="sender">The object that raised the event.</param>
        /// <param name="e">Elapsed event arguments.</param>
        /// </summary>
        private void OnTimerElapsed(object sender, ElapsedEventArgs e)
        {
            // Move log files older than 24 hours to the archive folder.
            MoveOldLogFiles();
            // Delete archived log files older than 72 hours.
            DeleteOldArchivedFiles();
        }

        /// Moves log files older than 24 hours from the log folder to the archive folder and handles potential file name conflicts.
        private void MoveOldLogFiles()
        {
            try
            {
                // Iterate through each file in the log folder.
                foreach (string file in Directory.GetFiles(logFolderPath))
                {
                    // Get the file's creation time.
                    DateTime creationTime = File.GetCreationTime(file);

                    // Check if the file is older than 24 hours.
                    if (DateTime.Now - creationTime > TimeSpan.FromHours(24))
                    {
                        // Construct the destination path in the archive folder.
                        string fileName = Path.GetFileName(file);
                        string destinationPath = Path.Combine(archiveFolderPath, fileName);

                        // Check if a file with the same name already exists in the archive folder.
                        if (File.Exists(destinationPath))
                        {
                            // If a file with the same name exists, add a timestamp to the file name to prevent overwriting.
                            string timestamp = DateTime.Now.ToString("yyyyMMddHHmmss");
                            destinationPath = Path.Combine(archiveFolderPath, $"{Path.GetFileNameWithoutExtension(fileName)}_{timestamp}{Path.GetExtension(fileName)}");
                        }

                        // Move the file from the log folder to the archive folder.
                        File.Move(file, destinationPath);

                        // Log the file move action.
                        LogManager.GetCurrentClassLogger().Info($"<=> Moved old log file to archive: {destinationPath}");
                    }
                }
            }
            catch (Exception ex)
            {
                // Log any errors encountered during the file move process.
                LogManager.GetCurrentClassLogger().Error(ex, "<=> Error moving old log files to archive.");
            }
        }

        /// Deletes archived log files that are older than 72 hours from the archive folder.
        private void DeleteOldArchivedFiles()
        {
            try
            {
                // Iterate through each file in the archive folder.
                foreach (string file in Directory.GetFiles(archiveFolderPath))
                {
                    // Get the file's creation time.
                    DateTime creationTime = File.GetCreationTime(file);

                    // Check if the file is older than 72 hours.
                    if (DateTime.Now - creationTime > TimeSpan.FromHours(72))
                    {
                        // Delete the file.
                        File.Delete(file);
                        // Log the file deletion action.
                        LogManager.GetCurrentClassLogger().Info($"<=> Deleted old archived log file: {file}");
                    }
                }
            }
            catch (Exception ex)
            {
                // Log any errors encountered during the file deletion process.
                LogManager.GetCurrentClassLogger().Error(ex, "<=> Error deleting old archived log files.");
            }
        }
    }
}