using System;
using System.IO;
using System.Timers;
using NLog;

namespace FxWorth
{
    /// <summary>
    /// The `ApiCompliance` class ensures compliance with the Deriv API terms and conditions regarding 'data storage'.
    /// It manages the log files generated by the application, moving older files to an archive folder 
    /// and deleting archived files that exceed the allowed retention period. This helps prevent 
    /// excessive data storage and ensures compliance with the API's data retention policies.
    /// </summary>
    public class ApiCompliance
    {
        private readonly string logFolderPath;
        private readonly string archiveFolderPath;
        private readonly Timer timer;
        public ApiCompliance(string logFolderPath, string archiveFolderPath)
        {
            this.logFolderPath = logFolderPath;
            this.archiveFolderPath = archiveFolderPath;

            if (!Directory.Exists(archiveFolderPath))
            {
                Directory.CreateDirectory(archiveFolderPath);
            }
            this.timer = new Timer(10 * 60 * 1000);
            this.timer.Elapsed += OnTimerElapsed;
        }

        public void Start()
        {
            timer.Start();
        }

        private void OnTimerElapsed(object sender, ElapsedEventArgs e)
        {
            MoveOldLogFiles();
            DeleteOldArchivedFiles();
        }

        private void MoveOldLogFiles()
        {
            try
            {
                foreach (string file in Directory.GetFiles(logFolderPath))
                {
                    DateTime creationTime = File.GetCreationTime(file);

                    if (DateTime.Now - creationTime > TimeSpan.FromHours(24))
                    {
                        string fileName = Path.GetFileName(file);
                        string destinationPath = Path.Combine(archiveFolderPath, fileName);

                        if (File.Exists(destinationPath))
                        {
                            string timestamp = DateTime.Now.ToString("yyyyMMddHHmmss");
                            destinationPath = Path.Combine(archiveFolderPath, $"{Path.GetFileNameWithoutExtension(fileName)}_{timestamp}{Path.GetExtension(fileName)}");
                        }

                        File.Move(file, destinationPath);
                        LogManager.GetCurrentClassLogger().Info($"<=> Moved old log file to archive: {destinationPath}");
                    }
                }
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error(ex, "<=> Error moving old log files to archive.");
            }
        }

        private void DeleteOldArchivedFiles()
        {
            try
            {
                foreach (string file in Directory.GetFiles(archiveFolderPath))
                {
                    DateTime creationTime = File.GetCreationTime(file);

                    if (DateTime.Now - creationTime > TimeSpan.FromHours(72))
                    {
                        File.Delete(file);
                        LogManager.GetCurrentClassLogger().Info($"<=> Deleted old archived log file: {file}");
                    }
                }
            }
            catch (Exception ex)
            {
                LogManager.GetCurrentClassLogger().Error(ex, "<=> Error deleting old archived log files.");
            }
        }
    }
}